version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: qna_db
      POSTGRES_USER: pg_test_qa
      POSTGRES_PASSWORD: pg_test_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./auth
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/qna_db
      - SPRING_DATASOURCE_USERNAME=pg_test_qa
      - SPRING_DATASOURCE_PASSWORD=pg_test_password

  document-service:
    build:
      context: ./document
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - auth-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/qna_db
      - SPRING_DATASOURCE_USERNAME=pg_test_qa
      - SPRING_DATASOURCE_PASSWORD=pg_test_password

  qna-service:
    build:
      context: ./qna
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - auth-service
      - document-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/qna_db
      - SPRING_DATASOURCE_USERNAME=pg_test_qa
      - SPRING_DATASOURCE_PASSWORD=pg_test_password

volumes:
  pgdata:
